### ISSUE TITLE
[Bug] Crash when wrenching a Solar Panel in IC2Mp

### ISSUE THREAD

**Issue by DanyGames2014** [FabricCompatibilityLayers/Apron#57]
**Affected mods:**
IC2Mp v1.337

## Describe the bug:
When right clicking with a electric wrench on a solar panel the game crashed

## To Reproduce:
1. Install Apron and the affected mod
2. Create a new world
3. Place down a solar panel
4. Try to wrench a solar panel with an electric wrench

## Expected behavior:
Not crash

## Actual behavior:
Crash

## Version info:
 - Apron version: `2.0.1`
 - Mod Remapping API `1.22.0`
 - StationAPI `2.0-alpha.2.1`

**Crash Report**
```
java.lang.IllegalAccessError: class mod_IC2Mp tried to access protected method 'int net.minecraft.class_17.method_1629(int)' (mod_IC2Mp and net.minecraft.class_17 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @65e579dc)
	at mod_IC2Mp.damageDroppedOfBlock(mod_IC2Mp.java:1434)
	at ic2.common.ItemToolWrench.onItemUseFirst(ItemToolWrench.java:95)
	at net.minecraft.class_504.handler$zck000$apron-impl$forge$IUseItemFirst(class_504.java:543)
	at net.minecraft.class_504.method_1713(class_504.java)
	at net.minecraft.client.Minecraft.method_2107(Minecraft.java:1130)
	at net.minecraft.client.Minecraft.method_2137(Minecraft.java:1337)
	at net.danygames2014.gambac.BrnoMinecraft.method_2137(BrnoMinecraft.java:62)
	at net.minecraft.client.Minecraft.run(Minecraft.java:754)
	at net.minecraft.client.MinecraftApplet.method_2153(MinecraftApplet.java:586)
	at net.minecraft.client.MinecraftApplet.md9dd1a6$gambac$lambda$init$0$0(MinecraftApplet.java:560)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by thecatcore** [comment]
can you send the `.tiny(v2)` files in `mod-remapping-api` sub folders?

**Comment by DanyGames2014** [comment]
These ones ? [1.22.0.zip](https://github.com/user-attachments/files/15510304/1.22.0.zip)

**Comment by thecatcore** [comment]
thx, it is indeed a MRAPI bug.
